---
- import_playbook: 01-setup-os.yml
- import_playbook: 02-setup-runtime.yml
- import_playbook: 03-setup-k8s.yml
- import_playbook: 04-addons.yml
- import_playbook: 05-gitops-observability.yml
- import_playbook: 06-gateway-exposure.yml